### ISSUE TITLE
Problems on Safari iOs

### ISSUE THREAD

**Issue by skerbis** [ninocamdzic/bgzy#1]
The Slides are not fixed in Safari 14.x - 15
Please can you help?

**Comment by ninocamdzic** [comment]
Hi skerbis. I unfortunately don't own a Mac but I will see what I can do.

**Comment by ninocamdzic** [comment]
Hi Skerbis,
Could you post your HTML and JavaScript here so I can take a look at it?

**Comment by skerbis** [comment]
I would like to send you the link but not here in public

**Comment by ninocamdzic** [comment]
I've managed to install Gnome Web to check if there are issues. Gnome Web is using WebKit as it's render engine. The pages I've provided in the repository render exactly the same as in all other browsers.

Can you recreate a similar page which can be used for testing? I rather not test a private website.

**Comment by ninocamdzic** [comment]
Can you further elaborate on the issue you are having? On an iOS 12.5 I'm having an issue in Safari where the background will jump a bit when the page has scrollbars (https://stackoverflow.com/questions/26464525/scrolling-issue-on-position-fixed-element-on-ios). Is this what you are experiencing?

**Comment by skerbis** [comment]
Yes it seems to be a similar issue.  i‘ll try to give you access

**Comment by skerbis** [comment]
Solved: There was an Error in my code. Sorry. A Special css has defined background-images for all Divs as fixed. 
:-) 
Thanks for this nice script.

**Comment by ninocamdzic** [comment]
No problem. Glad you've solved the issue. :-)
